import './styles/global.sass';
import './styles/body.sass';
import '../assets/he4rt-footer-white.png';
import './styles/logo.sass';
import './styles/footer.sass';
import './styles/backgroundForm.sass';
import './styles/loginForm.sass';
import './styles/registerForm.sass';
import '../assets/he4rt-footer-black.png';
